// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXn0lPa_4IIFsoHR8Xl5mymenw2vRdfg',
    appId: '1:632183724473:web:eac3fcf8a250966b3bbe68',
    messagingSenderId: '632183724473',
    projectId: 'cribbies-9553b',
    authDomain: 'cribbies-9553b.firebaseapp.com',
    storageBucket: 'cribbies-9553b.appspot.com',
    measurementId: 'G-PC6NLBCW3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7YPNW1Zk2k56Obbj4Wums8XN7z9ICOmk',
    appId: '1:632183724473:android:4f939b9215ebc8963bbe68',
    messagingSenderId: '632183724473',
    projectId: 'cribbies-9553b',
    storageBucket: 'cribbies-9553b.appspot.com',
  );
}
